FROM --platform=$BUILDPLATFORM oven/bun:alpine AS site_builder

WORKDIR /app

COPY . ./

RUN bun install --no-save --cwd ./internal/site \
    && bun run --cwd ./internal/site build

FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

RUN apk add --no-cache \
    unzip \
    ca-certificates

# Download Go modules
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy source files
COPY . ./
COPY --from=site_builder /app/internal/site/dist ./internal/site/dist

RUN update-ca-certificates

# Build
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /beszel ./internal/cmd/hub

# ? -------------------------
FROM scratch

COPY --from=builder /beszel /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Ensure data persistence across container recreations
VOLUME ["/beszel_data"]

EXPOSE 8090

ENTRYPOINT [ "/beszel" ]
CMD ["serve", "--http=0.0.0.0:8090"]
